export const FORMULARIO_ANUNCIO = 'FORMULARIO_ANUNCIO';
export const LISTADO_FAVORITOS = 'LISTADO_FAVORITOS';
export const DATOS_PERSONALES = 'DATOS_PERSONALES';
export const LISTADO_MIS_ANUNCIOS = 'LISTADO_MIS_ANUNCIOS';