export const FORMULARIO_ANUNCIO = 'FORMULARIO_ANUNCIO';
export const LISTADO_FAVORITOS = 'LISTADO_FAVORITOS';
export const DATOS_PERSONALES = 'DATOS_PERSONALES';
export const LISTADO_MIS_ANUNCIOS = 'LISTADO_MIS_ANUNCIOS';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';


export const MOSTRAR_MIS_ANUNCIOS = 'MOSTRAR_MIS_ANUNCIOS';





export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'MOSTRAR_MIS_ANUNCIOS';
export const LOGIN_EXITOSO= 'MOSTRAR_MIS_ANUNCIOS';
export const LOGIN_ERROR = 'MOSTRAR_MIS_ANUNCIOS';
export const CERRAR_SESION = 'MOSTRAR_MIS_ANUNCIOS';