export const FORMULARIO_ANUNCIO = 'FORMULARIO_ANUNCIO';
export const LISTADO_FAVORITOS = 'LISTADO_FAVORITOS';
export const DATOS_PERSONALES = 'DATOS_PERSONALES';
export const LISTADO_MIS_ANUNCIOS = 'LISTADO_MIS_ANUNCIOS';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';


export const MOSTRAR_MIS_ANUNCIOS = 'MOSTRAR_MIS_ANUNCIOS';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO= 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';


export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA= 'OCULTAR_ALERTA';